-- MySQL Script generated by MySQL Workbench
-- Tue Sep 20 22:09:52 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema summer
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `summer` ;

-- -----------------------------------------------------
-- Schema summer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `summer` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `summer` ;

-- -----------------------------------------------------
-- Table `summer`.`sys_power`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `summer`.`sys_power` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `summer`.`sys_power` (
  `id` VARCHAR(145) NOT NULL COMMENT '权限表id',
  `del_flag` INT NULL COMMENT '是否删除的标识字段,1正常,2删除',
  `menu_id` VARCHAR(145) NULL COMMENT '所属栏目的id',
  `name` VARCHAR(145) NULL COMMENT '权限名称',
  `description` VARCHAR(145) NULL COMMENT '简介',
  `icon` VARCHAR(45) NULL COMMENT '图标',
  `sort` INT NULL COMMENT '排序',
  `permission` VARCHAR(75) NULL COMMENT '权限标识',
  `is_show` INT NULL COMMENT '是否显示',
  `create_time` VARCHAR(45) NULL COMMENT '添加时间',
  `create_by` VARCHAR(145) NULL COMMENT '添加人',
  `update_time` VARCHAR(45) NULL COMMENT '更新时间',
  `update_by` VARCHAR(145) NULL COMMENT '更新人',
  `remark` VARCHAR(245) NULL COMMENT '备注信息',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '权限表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `summer`.`sys_menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `summer`.`sys_menu` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `summer`.`sys_menu` (
  `id` VARCHAR(145) NOT NULL COMMENT '菜单表id',
  `del_flag` INT NULL COMMENT '是否删除的标识字段,1正常,2删除',
  `place` INT NULL COMMENT '栏目位置,前台栏目/后台栏目',
  `parent_id` VARCHAR(145) NULL DEFAULT 'first' COMMENT '父级菜单id',
  `name` VARCHAR(145) NULL COMMENT '菜单名称',
  `description` VARCHAR(245) NULL COMMENT '菜单的详细描述',
  `href` VARCHAR(245) NULL COMMENT '连接地址',
  `target` VARCHAR(45) NULL COMMENT '目标(mainFrame,_blank,_self,_parent,_top)',
  `icon` VARCHAR(45) NULL COMMENT '图标',
  `sort` INT NULL COMMENT '排列顺序',
  `permission` VARCHAR(75) NULL COMMENT '权限标识',
  `is_show` INT NULL COMMENT '是否显示',
  `create_time` VARCHAR(45) NULL COMMENT '创建时间',
  `create_by` VARCHAR(145) NULL COMMENT '创建人',
  `update_time` VARCHAR(45) NULL COMMENT '修改时间',
  `update_by` VARCHAR(145) NULL COMMENT '修改人',
  `remark` VARCHAR(245) NULL COMMENT '备注',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '菜单表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `summer`.`wech_material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `summer`.`wech_material` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `summer`.`wech_material` (
  `id` VARCHAR(145) NOT NULL COMMENT '微信素材id',
  `del_flag` INT NULL COMMENT '是否删除的标识字段,1正常,2删除',
  `msg_type` VARCHAR(45) NULL COMMENT '素材类型',
  `key_word` VARCHAR(45) NULL COMMENT '关键字,客户获取素材的关键字(用来匹配用户发送过来的消息)',
  `media_id` VARCHAR(195) NULL COMMENT '素材id(用于处理非文字消息),可能是:image_id,music_id,video_id,voice_id',
  `content` VARCHAR(1945) NULL COMMENT '图文消息的具体内容，支持HTML标签，必须少于2万字符，小于1M，且此处会去除JS.同时也用于文本消息的内容',
  `name` VARCHAR(75) NULL COMMENT '文件名称,同时也用于媒体消息的名称',
  `url` VARCHAR(245) NULL COMMENT '1.图文页的URL，或者，当获取的列表是图片素材列表时，该字段是图片的URL.2.音乐链接,普通音乐(和url通用).3.同时其他素材的url也通用',
  `description` VARCHAR(345) NULL COMMENT '素材描述',
  `parent_media_id` VARCHAR(195) NULL COMMENT '单个文章所属的文图文图消息的id',
  `title` VARCHAR(145) NULL COMMENT '图文消息的标题',
  `thumb_media_id` VARCHAR(195) NULL COMMENT '图文消息的封面图片素材id（必须是永久mediaID）',
  `show_cover_pic` INT NULL COMMENT '是否在文章内部显示封面，0为false，即不显示，1为true，即显示',
  `author` VARCHAR(45) NULL COMMENT '作者',
  `digest` VARCHAR(95) NULL COMMENT '图文消息的摘要，仅有单图文消息才有摘要，多图文此处为空',
  `content_source_url` VARCHAR(245) NULL COMMENT '图文消息的原文地址，即点击“阅读原文”后的URL',
  `sort` INT NULL COMMENT '文图消息的顺序,以便记录多文图消息的先后值',
  `hq_music_url` VARCHAR(245) NULL COMMENT '高质量音乐链接，WIFI环境优先使用该链接播放音乐',
  `create_time` VARCHAR(45) NULL COMMENT '添加时间',
  `create_by` VARCHAR(145) NULL COMMENT '创建者',
  `update_time` VARCHAR(45) NULL COMMENT '更新时间',
  `update_by` VARCHAR(145) NULL COMMENT '更新者',
  `remark` VARCHAR(245) NULL COMMENT '备注信息',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '微信,用来存储素材的数据库';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `summer`.`wech_wechat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `summer`.`wech_wechat` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `summer`.`wech_wechat` (
  `id` VARCHAR(145) NOT NULL COMMENT 'id',
  `del_flag` INT NULL COMMENT '是否删除的标识字段,1正常,2删除',
  `wechat_key` VARCHAR(45) NULL COMMENT '用于验证的access_token',
  `wechat_value` VARCHAR(145) NULL COMMENT '用于刷新的refresh_token',
  `refresh_value` VARCHAR(145) NULL,
  `create_time` VARCHAR(45) NULL COMMENT '添加时间',
  `create_by` VARCHAR(145) NULL,
  `update_time` VARCHAR(45) NULL COMMENT '更新时间',
  `update_by` VARCHAR(145) NULL,
  `remark` VARCHAR(245) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '微信基础信息数据';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `summer`.`sys_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `summer`.`sys_user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `summer`.`sys_user` (
  `id` VARCHAR(145) NOT NULL COMMENT '用户id',
  `del_flag` INT NULL COMMENT '是否删除的标识字段,1正常,2删除',
  `user_name` VARCHAR(145) NULL COMMENT '用户名',
  `pwd` VARCHAR(245) NULL COMMENT '密码',
  `age` INT NULL COMMENT '年龄',
  `gender` INT NULL COMMENT '年龄',
  `phone` VARCHAR(145) NULL COMMENT '电话',
  `phone_state` INT NULL COMMENT '电话状态,是否绑定',
  `email` VARCHAR(145) NULL COMMENT '邮箱',
  `email_state` INT NULL COMMENT '邮件状态,是否绑定',
  `open_id` VARCHAR(145) NULL COMMENT '微信绑定时的openid',
  `wechat_state` INT NULL COMMENT '微信状态,是否绑定',
  `addr` VARCHAR(145) NULL COMMENT '外键',
  `company` INT NULL COMMENT '公司',
  `department` INT NULL COMMENT '部门',
  `position` INT NULL COMMENT '职位',
  `is_lock` INT NULL COMMENT '用户的可使用状态,1:正常,2:锁定',
  `create_time` VARCHAR(45) NULL COMMENT '添加时间',
  `create_by` VARCHAR(145) NULL,
  `update_time` VARCHAR(45) NULL COMMENT '更新时间',
  `update_by` VARCHAR(145) NULL,
  `remark` VARCHAR(245) NULL COMMENT '备注信息',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '用户表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `summer`.`sys_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `summer`.`sys_role` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `summer`.`sys_role` (
  `id` VARCHAR(145) NOT NULL COMMENT '角色表id',
  `del_flag` INT NULL COMMENT '伪删除标记字段',
  `name` VARCHAR(45) NULL COMMENT '角色名称',
  `enname` VARCHAR(45) NULL COMMENT '英文名称',
  `sort` INT NULL,
  `create_time` VARCHAR(45) NULL COMMENT '创建时间',
  `create_by` VARCHAR(145) NULL COMMENT '创建者',
  `update_time` VARCHAR(45) NULL COMMENT '更新时间',
  `update_by` VARCHAR(145) NULL COMMENT '更新者',
  `remark` VARCHAR(245) NULL COMMENT '备注',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '角色表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `summer`.`sys_user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `summer`.`sys_user_role` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `summer`.`sys_user_role` (
  `user_id` VARCHAR(145) NOT NULL COMMENT '用户外键',
  `role_id` VARCHAR(145) NOT NULL COMMENT '角色外键',
  PRIMARY KEY (`user_id`, `role_id`))
ENGINE = InnoDB
COMMENT = '用户角色中间表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `summer`.`sys_addr`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `summer`.`sys_addr` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `summer`.`sys_addr` (
  `id` VARCHAR(145) NOT NULL COMMENT '地址表id',
  `del_flag` INT NULL COMMENT '伪删除标记字段',
  `user_id` VARCHAR(145) NULL COMMENT '用户外键',
  `sort` INT NULL,
  `type` INT NULL COMMENT '地址类型,(和用户的关系)',
  `is_default` INT NULL COMMENT '是否是默认地址',
  `province` VARCHAR(45) NULL COMMENT '省/直辖市',
  `province_code` INT NULL COMMENT '省/直辖市编码',
  `city` VARCHAR(45) NULL COMMENT '市/县级市',
  `city_code` INT NULL COMMENT '市编码',
  `county` VARCHAR(45) NULL COMMENT '县',
  `county_code` INT NULL COMMENT '县编码',
  `info_addr` VARCHAR(245) NULL COMMENT '详细地址',
  `addressee` VARCHAR(45) NULL COMMENT '收件人',
  `phone` VARCHAR(45) NULL COMMENT '收件人电话',
  `create_time` VARCHAR(45) NULL COMMENT '创建时间',
  `create_by` VARCHAR(145) NULL COMMENT '创建者',
  `update_time` VARCHAR(45) NULL COMMENT '更新时间',
  `update_by` VARCHAR(145) NULL COMMENT '更新者',
  `remark` VARCHAR(245) NULL COMMENT '备注',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '地址表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `summer`.`sys_role_menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `summer`.`sys_role_menu` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `summer`.`sys_role_menu` (
  `role_id` VARCHAR(145) NOT NULL COMMENT '角色外键',
  `menu_id` VARCHAR(145) NOT NULL COMMENT '栏目外键',
  PRIMARY KEY (`role_id`, `menu_id`))
ENGINE = InnoDB
COMMENT = '角色栏目中间表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `summer`.`sys_role_power`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `summer`.`sys_role_power` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `summer`.`sys_role_power` (
  `role_id` VARCHAR(145) NOT NULL COMMENT '角色id外键',
  `power_id` VARCHAR(145) NOT NULL COMMENT '权限id外键',
  PRIMARY KEY (`role_id`, `power_id`))
ENGINE = InnoDB
COMMENT = '角色权限中间表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `summer`.`sys_file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `summer`.`sys_file` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `summer`.`sys_file` (
  `id` VARCHAR(145) NOT NULL COMMENT '文件表id',
  `del_flag` INT NULL COMMENT '伪删除字段',
  `sort` INT NULL COMMENT '排序',
  `source_name` VARCHAR(145) NULL COMMENT '原文件名',
  `name` VARCHAR(45) NULL COMMENT '文件名(现在的)',
  `src` VARCHAR(145) NULL COMMENT '文件路径',
  `size` INT NULL COMMENT '文件大小',
  `type` INT NULL COMMENT '文件类型',
  `suffix` VARCHAR(45) NULL COMMENT '文件后缀',
  `pojo_id` VARCHAR(145) NULL,
  `pojo_type` INT NULL,
  `create_time` VARCHAR(45) NULL COMMENT '创建时间',
  `create_by` VARCHAR(145) NULL COMMENT '创建人',
  `update_time` VARCHAR(45) NULL COMMENT '更新时间',
  `update_by` VARCHAR(145) NULL COMMENT '更新人',
  `remark` VARCHAR(245) NULL COMMENT '备注信息',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '文件表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `summer`.`sys_message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `summer`.`sys_message` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `summer`.`sys_message` (
  `id` VARCHAR(145) NOT NULL COMMENT '消息表id',
  `del_flag` INT NULL COMMENT '伪删除字段',
  `title` VARCHAR(75) NULL COMMENT '消息标题',
  `content` VARCHAR(245) NULL COMMENT '消息内容',
  `msg_from` VARCHAR(145) NULL COMMENT '消息发送者',
  `msg_to` VARCHAR(145) NULL COMMENT '消息接收者',
  `read_type` INT NULL COMMENT '消息阅读状态',
  `create_time` VARCHAR(45) NULL COMMENT '创建时间',
  `create_by` VARCHAR(145) NULL COMMENT '创建者',
  `update_time` VARCHAR(45) NULL COMMENT '更新时间',
  `update_by` VARCHAR(145) NULL COMMENT '更新者',
  `remark` VARCHAR(145) NULL COMMENT '备注',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '消息表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `summer`.`tools_mail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `summer`.`tools_mail` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `summer`.`tools_mail` (
  `id` VARCHAR(145) NOT NULL COMMENT '邮件表id',
  `del_flag` INT NULL COMMENT '伪删除字段',
  `subject` VARCHAR(145) NULL COMMENT '邮件主题',
  `text` VARCHAR(245) NULL COMMENT '邮件文本内容',
  `content` VARCHAR(445) NULL COMMENT '邮件主体内容',
  `modal_url` VARCHAR(145) NULL COMMENT '邮件对应的模型页面地址',
  `mail_key` VARCHAR(45) NULL COMMENT '邮件的识别键',
  `create_time` VARCHAR(45) NULL COMMENT '邮件记录的创建时间',
  `create_by` VARCHAR(145) NULL COMMENT '创建者',
  `update_time` VARCHAR(45) NULL COMMENT '更新时间',
  `update_by` VARCHAR(145) NULL COMMENT '更新者',
  `remark` VARCHAR(245) NULL COMMENT '备注信息',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '工具中,邮件表';

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
